<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            // Secrétaires
            [
                'nom' => 'Zinsou',
                'prenoms' => 'Mathieu',
                'role' => 'SECRETAIRE',
                'titre' => 'SECRETAIRE',
                'section_id' => 8,
                'structure_id' => 2,
                'email' => 'secretairegc1@gmail.com',
                'password' => Hash::make('secretairegc123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Houénou',
                'prenoms' => 'Clarisse',
                'role' => 'SECRETAIRE',
                'titre' => 'SECRETAIRE',
                'section_id' => 8,
                'structure_id' => 2,
                'email' => 'secretairegc2@gmail.com',
                'password' => Hash::make('secretairegc2123456789'),
                'sexe' => 'Femme',
            ],

            // Présidents de structure (conservés tels quels)
            [
                'nom' => 'Adjaho',
                'prenoms' => 'Aristide',
                'role' => 'PCJ',
                'titre' => 'PRESIDENT DE STRUCTURE',
                'section_id' => 8,
                'structure_id' => 2,
                'email' => 'pcj@gmail.com',
                'password' => Hash::make('pcj123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Tossou',
                'prenoms' => 'Jean-Eudes',
                'role' => 'PCA',
                'titre' => 'PRESIDENT DE STRUCTURE',
                'section_id' => 4,
                'structure_id' => 1,
                'email' => 'pca@gmail.com',
                'password' => Hash::make('pca123456789'),
                'sexe' => 'Homme',
            ],

            // Section 1 - Structure 1
            [
                'nom' => 'Sossa',
                'prenoms' => 'Ayodele',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 1,
                'structure_id' => 1,
                'email' => 'conseiller_c1s1a@gmail.com',
                'password' => Hash::make('conseiller_c1s1a123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Dossou',
                'prenoms' => 'Claude',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 1,
                'structure_id' => 1,
                'email' => 'conseiller_c1s1b@gmail.com',
                'password' => Hash::make('conseiller_c1s1b123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Ahouto',
                'prenoms' => 'Oscar',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 1,
                'structure_id' => 1,
                'email' => 'greffier_c1s1a@gmail.com',
                'password' => Hash::make('greffier_c1s1a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Dossè',
                'prenoms' => 'Clarisse',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 1,
                'structure_id' => 1,
                'email' => 'greffier_c1s1b@gmail.com',
                'password' => Hash::make('greffier_c1s1b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Houénou',
                'prenoms' => 'Nestor',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 1,
                'structure_id' => 1,
                'email' => 'auditeur_c1s1a@gmail.com',
                'password' => Hash::make('auditeur_c1s1a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Kpadé',
                'prenoms' => 'Mathias',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 1,
                'structure_id' => 1,
                'email' => 'auditeur_c1s1b@gmail.com',
                'password' => Hash::make('auditeur_c1s1b123456789'),
                'sexe' => 'Homme',
            ],

            // Section 2 - Structure 1
            [
                'nom' => 'Mensah',
                'prenoms' => 'Ako',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 2,
                'structure_id' => 1,
                'email' => 'conseiller_c1s2a@gmail.com',
                'password' => Hash::make('conseiller_c1s2a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Gbéto',
                'prenoms' => 'Nadège',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 2,
                'structure_id' => 1,
                'email' => 'conseiller_c1s2b@gmail.com',
                'password' => Hash::make('conseiller_c1s2b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Adjanohoun',
                'prenoms' => 'Armel',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 2,
                'structure_id' => 1,
                'email' => 'greffier_c1s2a@gmail.com',
                'password' => Hash::make('greffier_c1s2a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Houngbédji',
                'prenoms' => 'Sonia',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 2,
                'structure_id' => 1,
                'email' => 'greffier_c1s2b@gmail.com',
                'password' => Hash::make('greffier_c1s2b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Sagbo',
                'prenoms' => 'Jacques',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 2,
                'structure_id' => 1,
                'email' => 'auditeur_c1s2a@gmail.com',
                'password' => Hash::make('auditeur_c1s2a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Azonmè',
                'prenoms' => 'Laurent',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 2,
                'structure_id' => 1,
                'email' => 'auditeur_c1s2b@gmail.com',
                'password' => Hash::make('auditeur_c1s2b123456789'),
                'sexe' => 'Homme',
            ],

            // Section 3 - Structure 1
            [
                'nom' => 'Hounkpè',
                'prenoms' => 'Nadège',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 3,
                'structure_id' => 1,
                'email' => 'conseiller_c1s3a@gmail.com',
                'password' => Hash::make('conseiller_c1s3a123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Sèhoué',
                'prenoms' => 'Eric',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 3,
                'structure_id' => 1,
                'email' => 'conseiller_c1s3b@gmail.com',
                'password' => Hash::make('conseiller_c1s3b123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Avogbé',
                'prenoms' => 'Rachad',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 3,
                'structure_id' => 1,
                'email' => 'greffier_c1s3a@gmail.com',
                'password' => Hash::make('greffier_c1s3a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Azandé',
                'prenoms' => 'Marie-Claire',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 3,
                'structure_id' => 1,
                'email' => 'greffier_c1s3b@gmail.com',
                'password' => Hash::make('greffier_c1s3b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Agossou',
                'prenoms' => 'Hélène',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 3,
                'structure_id' => 1,
                'email' => 'auditeur_c1s3a@gmail.com',
                'password' => Hash::make('auditeur_c1s3a123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Sodokin',
                'prenoms' => 'Chantal',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 3,
                'structure_id' => 1,
                'email' => 'auditeur_c1s3b@gmail.com',
                'password' => Hash::make('auditeur_c1s3b123456789'),
                'sexe' => 'Femme',
            ],

            // Section 5 - Structure 2
            [
                'nom' => 'Dossou',
                'prenoms' => 'Félicien',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 5,
                'structure_id' => 2,
                'email' => 'conseiller_c2s5a@gmail.com',
                'password' => Hash::make('conseiller_c2s5a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Houénou',
                'prenoms' => 'Eugénie',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 5,
                'structure_id' => 2,
                'email' => 'conseiller_c2s5b@gmail.com',
                'password' => Hash::make('conseiller_c2s5b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Azonmè',
                'prenoms' => 'Laurent',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 5,
                'structure_id' => 2,
                'email' => 'greffier_c2s5a@gmail.com',
                'password' => Hash::make('greffier_c2s5a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Ahounou',
                'prenoms' => 'Josiane',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 5,
                'structure_id' => 2,
                'email' => 'greffier_c2s5b@gmail.com',
                'password' => Hash::make('greffier_c2s5b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Dossou',
                'prenoms' => 'Sonia',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 5,
                'structure_id' => 2,
                'email' => 'auditeur_c2s5a@gmail.com',
                'password' => Hash::make('auditeur_c2s5a123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Houngbédji',
                'prenoms' => 'Armelle',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 5,
                'structure_id' => 2,
                'email' => 'auditeur_c2s5b@gmail.com',
                'password' => Hash::make('auditeur_c2s5b123456789'),
                'sexe' => 'Femme',
            ],

            // Section 6 - Structure 2
            [
                'nom' => 'Adéhou',
                'prenoms' => 'Hervé',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 6,
                'structure_id' => 2,
                'email' => 'conseiller_c2s6a@gmail.com',
                'password' => Hash::make('conseiller_c2s6a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Gansou',
                'prenoms' => 'Diane',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 6,
                'structure_id' => 2,
                'email' => 'conseiller_c2s6b@gmail.com',
                'password' => Hash::make('conseiller_c2s6b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Ahissou',
                'prenoms' => 'Abdoulaye',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 6,
                'structure_id' => 2,
                'email' => 'greffier_c2s6a@gmail.com',
                'password' => Hash::make('greffier_c2s6a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Tognon',
                'prenoms' => 'Clarisse',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 6,
                'structure_id' => 2,
                'email' => 'greffier_c2s6b@gmail.com',
                'password' => Hash::make('greffier_c2s6b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Gbaguidi',
                'prenoms' => 'Marcel',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 6,
                'structure_id' => 2,
                'email' => 'auditeur_c2s6a@gmail.com',
                'password' => Hash::make('auditeur_c2s6a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Gbaguidi',
                'prenoms' => 'Mario',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 6,
                'structure_id' => 2,
                'email' => 'auditeur_c2s6b@gmail.com',
                'password' => Hash::make('auditeur_c2s6b123456789'),
                'sexe' => 'Homme',
            ],

            // Section 7 - Structure 2
            [
                'nom' => 'Kpanou',
                'prenoms' => 'Aurélien',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 7,
                'structure_id' => 2,
                'email' => 'conseiller_c2s7a@gmail.com',
                'password' => Hash::make('conseiller_c2s7a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Kinkpé',
                'prenoms' => 'Alice',
                'role' => 'CONSEILLER',
                'titre' => 'CONSEILLER',
                'section_id' => 7,
                'structure_id' => 2,
                'email' => 'conseiller_c2s7b@gmail.com',
                'password' => Hash::make('conseiller_c2s7b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Madogni',
                'prenoms' => 'Gildas',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 7,
                'structure_id' => 2,
                'email' => 'greffier_c2s7a@gmail.com',
                'password' => Hash::make('greffier_c2s7a123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Bognon',
                'prenoms' => 'Florence',
                'role' => 'GREFFIER',
                'titre' => 'GREFFIER',
                'section_id' => 7,
                'structure_id' => 2,
                'email' => 'greffier_c2s7b@gmail.com',
                'password' => Hash::make('greffier_c2s7b123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Lokossou',
                'prenoms' => 'Marina',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 7,
                'structure_id' => 2,
                'email' => 'auditeur_c2s7a@gmail.com',
                'password' => Hash::make('auditeur_c2s7a123456789'),
                'sexe' => 'Femme',
            ],
            [
                'nom' => 'Mandi',
                'prenoms' => 'Marina',
                'role' => 'AUDITEUR',
                'titre' => 'AUDITEUR',
                'section_id' => 7,
                'structure_id' => 2,
                'email' => 'auditeur_c2s7b@gmail.com',
                'password' => Hash::make('auditeur_c2s7b123456789'),
                'sexe' => 'Femme',
            ],

            // Super Admins
            [
                'nom' => 'CAKPO',
                'prenoms' => 'Allégresse',
                'role' => 'SUPER ADMIN',
                'titre' => 'SUPER ADMIN',
                'email' => 'allegressecakpo93@gmail.com',
                'password' => Hash::make('adminpos3123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'Nassirou',
                'prenoms' => 'Abdoul',
                'role' => 'SUPER ADMIN',
                'titre' => 'SUPER ADMIN',
                'email' => 'akarimou@coursupreme.bj',
                'password' => Hash::make('adminpos2123456789'),
                'sexe' => 'Homme',
            ],
            [
                'nom' => 'OUSMANE',
                'prenoms' => 'Abdoul Matine',
                'role' => 'SUPER ADMIN',
                'titre' => 'SUPER ADMIN',
                'email' => 'abdoul.ousmane@coursupreme.bj',
                'password' => Hash::make('adminpos1123456789'),
                'sexe' => 'Homme',
            ],
        ];

        foreach ($users as $user) {
            User::create($user);
        }
    }
}
